MovieProjectAssignment/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieProjectAssignment.Models;
using MovieProjectAssignment.Models.ViewModels;

namespace MovieProjectAssignment.Controllers
{
    public class CustomerController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Customer
        public ActionResult Index()
        {
            return View(db.Customers.ToList());
        }

           /*  Notes
            *  The requirement: "Each order for the user should then be displayed together with the movies belonging to the order (orderrows).
            *   Also, the total cost for the order should be displayed". "Each order should be rendered using a partial view".
            *   
            *   I have used nestled lists. List of NewViewOrdersVM that contains List of MovieNameAndPrice.
            *   NewViewOrderVM contains multiple orders. Every order has usually contains multiple movies.
            *   This is done primaraly to satisfy the partial view requirement. 
            *   
            *   I'm aware that the primary LINQ-query could include OrderDate. 
            */
        public ActionResult Details(int? id) // Id in this case is Customer Id
        {
            Customer customer = db.Customers.Find(id);

            // List of distinct Orders from Customers
            var OrdersOfCustomers = db.Orders.Where(CId => CId.CustomerId == id).Select(x => x.Id).Distinct().ToList();

            // Get MovieTitle, Price and OrderId for Customer with id as parameter
            var TitlePriceOrdId = db.OrderRows.Join(db.Orders, m => m.OrderId, r => r.Id, (m, r) => new { m, r })
                 .Join(db.Movies, mr => mr.m.MovieId, o => o.Id, (mr, o) => new { mr, o })
                 .Where(mrx => mrx.mr.r.CustomerId == id)
              .Select(mro => new MovieNameAndPrice { MovieName = mro.o.Title, Price = mro.mr.m.Price, OrderId = mro.mr.m.OrderId }).ToList();

            List<ViewOrdersVM> ListOfVMs = new List<ViewOrdersVM>();

            ViewOrdersVM TempVM;
            foreach(var n in OrdersOfCustomers) // Populate list of orders from customer
            {
                TempVM = new ViewOrdersVM();
                TempVM.OrderDate = db.Orders.Where(x => x.Id == n).Select(y => y.OrderDate).FirstOrDefault(); // OrderDate in Order Model
                TempVM.OrderNumber = n; // OrderID in Order Model
                TempVM.ListOfMoviesAndPrice = TitlePriceOrdId.Where(x => x.OrderId == n).ToList(); // List of Movie titles and Price
                ListOfVMs.Add(TempVM);
            }

            return View(ListOfVMs);
        }
    }
}

MovieProjectAssignment/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieProjectAssignment.Models;
using MovieProjectAssignment.Models.ViewModels;



namespace MovieProjectAssignment.Controllers
{
    public class MovieController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //[HttpGet]
        public ActionResult ListMovies()
        {

            // ShoppingCartController.InitCart();
            //RedirectToAction("InitCart", "ShoppingCart");

            //ShoppingCartController callInit = new ShoppingCartController();
            //callInit.InitCart();

            if (Session["Cart"] == null)
            {
                ShoppingCart tempCart = new ShoppingCart();
                tempCart.MoviesInCart = new List<Movie>();
                Session["Cart"] = tempCart;
            }

            return View(db.Movies.ToList());
        }

        public ActionResult ListMoviesAddToCart(int? id)
        {
            //Session["Cart"] += id.ToString() + " ";
            Movie movie = db.Movies.Find(id);
            ShoppingCart tempCart = Session["Cart"] as ShoppingCart;
            tempCart.MoviesInCart.Add(movie);
            Session["Cart"] = tempCart;

            return View("ListMovies", db.Movies.ToList());
        }

        // string ViewCart works

        //public string ViewCart()
        //{
        //    ShoppingCart tempCart = Session["Cart"] as ShoppingCart;
        //    var returnString = "";
        //    foreach(var item in tempCart.MoviesInCart)
        //    {
        //        returnString += item.Id.ToString() + "\n";
        //        returnString += item.Title.ToString() + "\n";
        //        returnString += item.Director.ToString() + "\n";
        //        returnString += item.ReleaseYear.ToString() + "\n";
        //        returnString += item.Price.ToString() + "\n";
        //    }
        //    return returnString;
        //}

        // I'm unsure how to make the shopping cart with an overloaded ListMovies that uses HttpPost
        // The model is used to display the movies already. So a Form-submit would not work

        // Couldnt get Overloaded ListMovies to work, the one with int? id. Results in error ambigous reference
        // Changeing Action-name does not work

        //[HttpPost]
        //[ActionName("ListMoviesWithId")]
        //public ActionResult ListMovies(int? id)
        //{
        //    ShoppingCart tempCart = new ShoppingCart();
        //    Session["Cart"] += id.ToString();
        //    return View(db.Movies.ToList());
        //}


        // Requirements, add a movie with title, director, release year and price
        [HttpGet]
        public ActionResult AddMovie()
        {
            Movie refMovie = new Movie();

            return View(refMovie);
        }

        [HttpPost]
        public ActionResult AddMovie(Movie movie)
        {
            db.Movies.Add(movie);
            db.SaveChanges();
            ViewBag.Message = "The Movie was added.";

            return View(movie);
        }
    }
}

MovieProjectAssignment/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MovieProjectAssignment.Models;

namespace MovieProjectAssignment.Controllers
{
    public class ShoppingCartController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult ViewCart()
        {
            InitCart();
            ShoppingCart tempCart = Session["Cart"] as ShoppingCart;
            return View(tempCart.MoviesInCart);
        }

        public ActionResult EmptyCart()
        {
            Session["Cart"] = null;
            InitCart();
            ShoppingCart tempCart = Session["Cart"] as ShoppingCart;
            return RedirectToAction("ViewCart");
        }
        public ActionResult PlaceOrderNewCustomer()
        {
            Customer emptyCustomer = new Customer();
            return View(emptyCustomer);
        }

        [HttpPost]
        public ActionResult PlaceOrderNewCustomer(Customer submitCustomer)
        {
            // Add new customer to database
            db.Customers.Add(submitCustomer);
            db.SaveChanges();

            // Get the newly added customer, we need to know the id
            Customer latestCustomerFromDB = db.Customers.ToList().LastOrDefault();
            int newCustomerId = latestCustomerFromDB.Id;
            
            // Load shoppingcart from session
            ShoppingCart tempCart = Session["Cart"] as ShoppingCart;

            // Create order and orderrow objects
            Order newOrder = new Order();
            OrderRow newOrderRow;

            newOrder.OrderDate = DateTime.Now;
            newOrder.CustomerId = newCustomerId;
            db.Orders.Add(newOrder); // Add the new order
            db.SaveChanges();

            // We need to know the id of the newly created order
            Order latestOrder = db.Orders.ToList().LastOrDefault();
            int latestOrderId = latestOrder.Id;

            // add movies from shopping cart to orderrows, one by one
            foreach (Movie tempMovie in tempCart.MoviesInCart)
            {
                newOrderRow = new OrderRow();
                newOrderRow.OrderId = latestOrderId;
                newOrderRow.MovieId = tempMovie.Id;
                newOrderRow.Price = tempMovie.Price;
                db.OrderRows.Add(newOrderRow);
            }

            db.SaveChanges();

            return RedirectToAction("PlaceOrderSuccess");
        }

        // Place order for existing user
        public ActionResult PlaceOrderExistingCustomer()
        {
            Customer emptyCustomer = new Customer();
            return View(emptyCustomer);
        }

        [HttpPost]
        public ActionResult PlaceOrderExistingCustomer(Customer submitCustomer)
        {
            Customer findCustomer = db.Customers.Where(eMail => eMail.EmailAddress == submitCustomer.EmailAddress).FirstOrDefault();

            if (findCustomer == null) // If email is not found, goto form for new user
            {
                return RedirectToAction("PlaceOrderNewCustomer");
            }

            ShoppingCart tempCart = Session["Cart"] as ShoppingCart;

            // Id, OrderDate, CustomerId
            Order newOrder = new Order();
            OrderRow newOrderRow;

            newOrder.OrderDate = DateTime.Now;
            newOrder.CustomerId = findCustomer.Id;
            db.Orders.Add(newOrder); // Create a new order entry
            db.SaveChanges();

            Order latestOrder = db.Orders.ToList().LastOrDefault();
            int latestOrderId = latestOrder.Id;

            // Id, OrderId, MovieId, Price
            foreach (Movie tempMovie in tempCart.MoviesInCart) // add movies from shopping cart to orderrows, one by one
            {
                newOrderRow = new OrderRow();
                newOrderRow.OrderId = latestOrderId;
                newOrderRow.MovieId = tempMovie.Id;
                newOrderRow.Price = tempMovie.Price;
                db.OrderRows.Add(newOrderRow);
            }

            db.SaveChanges();
            return RedirectToAction("PlaceOrderSuccess");
        }

        public ActionResult PlaceOrderSuccess()
        {
            // Clear cart when order is placed
            Session["Cart"] = null;
            InitCart();

            return View();
        }

        // Add another item to shopping cart
        public ActionResult AddItem(int? id)
        {
            ShoppingCart tempCart = Session["Cart"] as ShoppingCart;

            var item = tempCart.MoviesInCart.FirstOrDefault(x => x.Id == id);
            if (item != null)
                tempCart.MoviesInCart.Add(item);

            Session["Cart"] = tempCart;
            
            return View("ViewCart", tempCart.MoviesInCart);
        }

        // Remove item from shopping cart
        public ActionResult RemoveItem(int? id)
        {
            ShoppingCart tempCart = Session["Cart"] as ShoppingCart;

            var item = tempCart.MoviesInCart.FirstOrDefault(x => x.Id == id);
            if (item != null)
                tempCart.MoviesInCart.Remove(item);

            // Save changes
            Session["Cart"] = tempCart;

            return View("ViewCart", tempCart.MoviesInCart);
        }

        public void InitCart()
        {
            if (Session["Cart"] == null)
            {
                ShoppingCart tempCart = new ShoppingCart();
                tempCart.MoviesInCart = new List<Movie>();
                Session["Cart"] = tempCart;
            }
        }
    }
}

MovieProjectAssignment/Views/Shared/_DisplayCustomerOrders.cshtml
@model  MovieProjectAssignment.Models.ViewModels.ViewOrdersVM

    @{ decimal totalPrice = 0; }

    <table class="table">

        <tr>
            <th>Movie</th>
            <th>Price</th>
        </tr>

        @foreach (var item in Model.ListOfMoviesAndPrice)
        {
            <tr>
                <td>@item.MovieName</td>
                <td>@item.Price</td>
            </tr>

            totalPrice += item.Price;
        }

    </table>

    <p>Total price: @totalPrice  Order Id: @Model.OrderNumber Order Date: @Model.OrderDate</p>

MovieProjectAssignment/Views/Shared/_Layout.cshtml
@using MovieProjectAssignment.Models

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<title>@ViewBag.Title - My ASP.NET Application</title>*@
    <title>Movie Project Assignment</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Movie Project Assignment", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Add Movie", "AddMovie", "Movie")</li>
                    <li>@Html.ActionLink("List of Movies", "ListMovies", "Movie")</li>
                    <li>@Html.ActionLink("View Customer Orders", "Index", "Customer")</li>
                    <li>

                        @{
                            int itemsInCart = 0;
                            // Display number of items in shopping cart
                            if (Session["Cart"] != null) // If the cart is populated
                            {

                                //List<Movie> shoppingCart = Session["Cart"] as List<Movie>;
                                ShoppingCart tempCart = Session["Cart"] as ShoppingCart;
                                if (tempCart != null)
                                {
                                    itemsInCart = tempCart.MoviesInCart.Count();
                                }
                            }
                        }
                        @Html.ActionLink("Shopping Cart (" + itemsInCart + ")", "ViewCart", "ShoppingCart");
                    </li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@

            </div>
        </div>
    </div>
    <div class="container body-content">
        <br />
        @RenderBody()
        @*<hr />*@
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
            @*<p>&copy; @DateTime.Now.Year - Movie Project</p>*@
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MovieProjectAssignment/Views/Shared/_displaymovie.cshtml
@model MovieProjectAssignment.Models.Movie

<table>
    <tr>
        <th>
            <p>Title: @Model.Title</p>
        </th>
    </tr>
    <tr>
        <th>
            <p>Director: @Model.Director</p> 
        </th>
    </tr>
    <tr>
        <th>
            <p>Release Year: @Model.ReleaseYear</p>
        </th>
    </tr>
    <tr>
        <th>
            <p>Price: @Model.Price</p>
        </th>
    </tr>
</table>